let soundLibrary = {
	chirps: {},
	fades: {},
	soundtracks: []
}


// --- Reverb (2026-06-21) --------------------------------------------------
// Baseline reverb on every chirp and fade: each sound gets its own reverb at
// load (see loadSoundFolder), giving the whole voice a consistent sense of
// space. randomChirp() raises the mix when Mima is "far" (perspective > 3) so
// she sounds more distant. Tweak these to taste.
let reverbSettings = {
	time: 3.4,        // reverb tail length, seconds — long, so it lingers
	decay: 0.3,       // lower = more sustain through the tail (don't die off early)
	reverse: false,   // true = swelling/reverse reverb; false = natural tail
	mix: 0.5,         // baseline wet/dry mix — wet, so everything shares one room
	farMix: 0.8,      // even wetter when Mima is far away (perspective > 3)
}
function makeReverb() {
	return new Pizzicato.Effects.Reverb({
		time: reverbSettings.time,
		decay: reverbSettings.decay,
		reverse: reverbSettings.reverse,
		mix: reverbSettings.mix,
	})
}

function randomChirp(length) {



	let keys = Object.keys(soundLibrary.chirps)
	if (keys.length !== 0) {
		let key = getRandom(keys)
		let sound = soundLibrary.chirps[key]

		// Per-file levelling gain from the manifest (see serve.js): brings every
		// blip/chirp to a consistent peak so the hot ones don't jump out / clip.
		let gain = sound._gain || 1
		sound.volume = app.values.volume*settings.volume*gain
		// Baseline reverb is always on (added at load); when Mima is far away she
		// goes quieter and the reverb gets wetter so she sounds distant.
		if (sound._reverb) sound._reverb.mix = reverbSettings.mix
		if (app.values.perspective > 3) {
			sound.volume *= .1
			if (sound._reverb) sound._reverb.mix = reverbSettings.farMix
		}


		sound.play()

		sound.sourceNode.playbackRate.value = (Math.pow(.92, app.values.speed + .01))*settings.speed / (length*.001 + 1 + Math.random())
		sound.on('end', () => {
			// console.log("done!")
		})
	}
}


// Load every file from a sounds subfolder into a soundLibrary pool. Filenames
// are NOT hardcoded: we fetch the folder's manifest.json (generated by
// serve.js), which lists each { file, gain }. The `gain` levels the file to a
// consistent peak (see serve.js) and is stashed on the sound. So dropping new
// wavs into the folder loads AND auto-levels them with no code edit.
function loadSoundFolder(folder, poolName) {
	fetch('mima/sounds/' + folder + '/manifest.json')
		.then(res => res.json())
		.then(entries => {
			entries.forEach((entry) => {
				// Tolerate the old plain-string manifest format too.
				let file = (typeof entry === 'string') ? entry : entry.file
				let gain = (typeof entry === 'string') ? 1 : entry.gain
				let key = folder + '/' + file
				var sound = new Pizzicato.Sound({
					source: 'file',
					options: { path: 'mima/sounds/' + folder + '/' + file }
				}, ()  => {
					sound._gain = gain
					// Each chirp/fade gets its own baseline reverb for a shared sense
					// of space (created here as the file loads, so the cost spreads
					// out rather than building 50 impulses at once).
					let rev = makeReverb()
					sound.addEffect(rev)
					sound._reverb = rev
					soundLibrary[poolName][key] = sound
					console.log(`${poolName} loaded: '${key}' (gain ${gain})`);
					// If the player already pressed "Hello?" before the fades had
					// loaded, fire the promised intro fade once one is available.
					if (introFadePending && playFade()) introFadePending = false
				});
			})
		})
		.catch(err => console.warn('could not load manifest for ' + folder, err))
}

// Play one fade/transition sound, once. Called on every state change (see
// app.js onEnterState). Uses settings.volume so it stays consistent regardless
// of the per-state voice volume.
function playFade() {
	let keys = Object.keys(soundLibrary.fades)
	if (keys.length === 0) return false
	let sound = soundLibrary.fades[getRandom(keys)]
	sound.volume = settings.volume * (sound._gain || 1)
	sound.play()
	return true
}


// Intro fade: a single fade/transition sound the instant the player presses
// "Hello?", so the press has an immediate audible effect before Mima arrives.
// Plays now if the fades have loaded, otherwise arms a flag so the first fade
// to finish loading fires it (loading is async, usually <100ms).
let introFadePending = false
function fadeWhenReady() {
	if (!playFade()) introFadePending = true
}


function startSoundtrack() {
	if (currentSoundtrack === undefined)  {
		console.log("🎵: start soundtrack")
		if (soundLibrary.soundtracks.length > 0) {
			currentSoundtrack = soundLibrary.soundtracks[0]
			currentSoundtrack.play()
		} else {
			playSoundtrackOnLoad = true
		}
	} else {
		console.log("🎵: - soundtrack already playing -")

	}
}

let playSoundtrackOnLoad = false
let currentSoundtrack = undefined
let soundInitialized = false

function initSounds() {
	if (!soundInitialized) {
		soundInitialized = true
		console.log("RESUME SOUND")
	Pizzicato.context.resume();

	// Voice = blips/ + chirps/, both folded into the same randomChirp() pool.
	// Fades = one-shot transition whooshes (played by playFade on state change).
	// All levelled per-file via their manifests (see loadSoundFolder / serve.js).
	loadSoundFolder('blips', 'chirps')
	loadSoundFolder('chirps', 'chirps')
	loadSoundFolder('fades', 'fades')

	// Background soundtrack — full filename incl. extension so .wav/.mp3 both work.
	let soundtrackFiles = ["kettleSimple01.mp3"]
	soundtrackFiles.forEach((name) => {
		var sound = new Pizzicato.Sound({
			source: 'file',
			loop: true,
			options: { path: 'mima/sounds/' + name }
		}, ()  => {
			console.log(`soundtrack file loaded: '${name}'`);
			//	sound.play();
			soundLibrary.soundtracks.push(sound)
			if (playSoundtrackOnLoad)
				startSoundtrack()
		});

	})
	}
}
