let soundLibrary = {
	chirps: {},
	fades: {},
	soundtracks: []
}


let effects = {
	reverb: new Pizzicato.Effects.Reverb({
		time: 3.4,
		decay: 0.3,
		reverse: false,
		mix: 0,
	})
}

function randomChirp(length) {
	let keys = Object.keys(soundLibrary.chirps)
	if (keys.length === 0) return

	let key = getRandom(keys)
	let sound = soundLibrary.chirps[key]

	sound.volume = app.values.volume * settings.volume
	if (app.values.perspective > 3) {
		sound.volume *= .1
		effects.reverb.mix = 0.3
	} else {
		effects.reverb.mix = 0
	}

	sound.play()

	if (sound.sourceNode) {
		const rate = (Math.pow(.92, app.values.speed + .01)) * settings.speed / (length * .001 + 1 + Math.random())
		sound.sourceNode.playbackRate.setValueAtTime(rate, Pizzicato.context.currentTime)
	}
}


// Load every file from a sounds subfolder into a soundLibrary pool. Filenames
// are NOT hardcoded: we fetch the folder's manifest.json (generated by
// serve.js), which lists each { file, gain }. The `gain` levels the file to a
// consistent peak (see serve.js) and is stashed on the sound. So dropping new
// wavs into the folder loads AND auto-levels them with no code edit.
function loadSoundFolder(folder, poolName) {
	fetch('mima/sounds/' + folder + '/manifest.json')
		.then(res => res.json())
		.then(entries => {
			entries.forEach((entry) => {
				// Tolerate the old plain-string manifest format too.
				let file = (typeof entry === 'string') ? entry : entry.file
				let gain = (typeof entry === 'string') ? 1 : entry.gain
				let key = folder + '/' + file
				var sound = new Pizzicato.Sound({
					source: 'file',
					options: { path: 'mima/sounds/' + folder + '/' + file }
				}, ()  => {
					sound._gain = gain
					sound.addEffect(effects.reverb)
					soundLibrary[poolName][key] = sound
					console.log(`${poolName} loaded: '${key}' (gain ${gain})`);
					// If the player already pressed "Hello?" before the fades had
					// loaded, fire the promised intro fade once one is available.
					if (introFadePending && playFade()) introFadePending = false
				});
			})
		})
		.catch(err => console.warn('could not load manifest for ' + folder, err))
}

// Play one fade/transition sound, once. Called on every state change (see
// app.js onEnterState). Uses settings.volume so it stays consistent regardless
// of the per-state voice volume.
function playFade() {
	let keys = Object.keys(soundLibrary.fades)
	if (keys.length === 0) return false
	let sound = soundLibrary.fades[getRandom(keys)]
	sound.volume = settings.volume * (sound._gain || 1)
	sound.play()
	return true
}


// Intro fade: a single fade/transition sound the instant the player presses
// "Hello?", so the press has an immediate audible effect before Mima arrives.
// Plays now if the fades have loaded, otherwise arms a flag so the first fade
// to finish loading fires it (loading is async, usually <100ms).
let introFadePending = false
function fadeWhenReady() {
	if (!playFade()) introFadePending = true
}


function startSoundtrack() {
	if (currentSoundtrack === undefined)  {
		console.log("🎵: start soundtrack")
		if (soundLibrary.soundtracks.length > 0) {
			currentSoundtrack = soundLibrary.soundtracks[0]
			currentSoundtrack.play()
		} else {
			playSoundtrackOnLoad = true
		}
	} else {
		console.log("🎵: - soundtrack already playing -")

	}
}

let playSoundtrackOnLoad = false
let currentSoundtrack = undefined
let soundInitialized = false

function initSounds() {
	if (!soundInitialized) {
		soundInitialized = true
		console.log("RESUME SOUND")
	Pizzicato.context.resume();

	// Voice = blips/ + chirps/, both folded into the same randomChirp() pool.
	// Fades = one-shot transition whooshes (played by playFade on state change).
	// All levelled per-file via their manifests (see loadSoundFolder / serve.js).
	loadSoundFolder('blips', 'chirps')
	loadSoundFolder('chirps', 'chirps')
	loadSoundFolder('fades', 'fades')

	// Background soundtrack — full filename incl. extension so .wav/.mp3 both work.
	let soundtrackFiles = ["kettleSimple01.mp3"]
	soundtrackFiles.forEach((name) => {
		var sound = new Pizzicato.Sound({
			source: 'file',
			loop: true,
			options: { path: 'mima/sounds/' + name }
		}, ()  => {
			console.log(`soundtrack file loaded: '${name}'`);
			//	sound.play();
			soundLibrary.soundtracks.push(sound)
			if (playSoundtrackOnLoad)
				startSoundtrack()
		});

	})
	}
}
